/-
Paper 3, seventh tranche: the first bricks of T1's Rips program
(docs/paper3/THEORY.md, "Lemma B", "Lemma D⁻").

Mathlib has no Vietoris–Rips persistence, and the ledger records that gap.
But T1's proved lemmas do not actually run on persistence machinery — they
run on plane geometry and a linear functional, and THAT is formalizable now:

  * `chordSq_eq` (law of cosines) — the squared chord between polar points
    is `r₁² + r₂² − 2r₁r₂·cos(θ₁−θ₂)`, exactly.
  * `wrap`, `cos_wrap` — angular increments wrapped to `(−π, π]` via
    `Real.Angle`; cosine does not see the wrap.
  * `wrap_lt_of_chordSq_lt` — **the edge–angle bound of Lemma D⁻**: an edge
    of chord < √3·r_min between points at radii ≥ r_min has wrapped angular
    increment strictly inside `(−2π/3, 2π/3)` (via cos > −1/2 and the
    antitonicity of cos on `[0, π]`).
  * `wrap_triangle_sum`, `triangle_wrap_sum_eq_zero` — the increments of a
    triangle telescope to a multiple of 2π, and when each is < 2π/3 in
    absolute value that multiple is EXACTLY zero — the paper's "every
    triangle boundary has winding 0".
  * `winding`, `triangleBoundary`, `winding_notin_boundaries`,
    `lemmaDminus_core` — 1-chains as finitely supported ℤ-combinations of
    oriented edges, winding as the induced additive functional, and
    **Lemma D⁻'s mathematical content**: a chain with nonzero winding is not
    in the subgroup generated by the boundaries of triangles all of whose
    edges have chord ≤ s, whenever s² < 3·r_min². "The winding class is not
    a boundary below √3·r_min" — with the persistence bookkeeping stripped,
    exactly as the paper's own proof strips it.

Not formalized here (the honest frontier): the Rips-complex/persistence
LANGUAGE (birth/death of the bar, the class-to-bar transfer Lemma P) and
Lemma B's existence half (the consecutive-neighbors cycle at the birth
scale) — the objects exist in this file's terms, but the full T1 sandwich
law is a program, not a tranche. This file is its foundation layer.
-/
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Angle
import Mathlib.Data.Finsupp.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.Floor.Defs
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.LinearCombination

namespace Paper3Ring

namespace RipsCircle

open Real

/-! ## Chords and wrapped increments -/

/-- Squared chord between the polar points `(r₁, θ₁)` and `(r₂, θ₂)`. -/
noncomputable def chordSq (r₁ θ₁ r₂ θ₂ : ℝ) : ℝ :=
  (r₁ * cos θ₁ - r₂ * cos θ₂) ^ 2 + (r₁ * sin θ₁ - r₂ * sin θ₂) ^ 2

/-- The law of cosines, exactly. -/
lemma chordSq_eq (r₁ θ₁ r₂ θ₂ : ℝ) :
    chordSq r₁ θ₁ r₂ θ₂ = r₁ ^ 2 + r₂ ^ 2 - 2 * r₁ * r₂ * cos (θ₁ - θ₂) := by
  have h₁ := sin_sq_add_cos_sq θ₁
  have h₂ := sin_sq_add_cos_sq θ₂
  rw [chordSq, cos_sub]
  linear_combination (r₁ ^ 2) * h₁ + (r₂ ^ 2) * h₂

lemma chordSq_comm (r₁ θ₁ r₂ θ₂ : ℝ) :
    chordSq r₁ θ₁ r₂ θ₂ = chordSq r₂ θ₂ r₁ θ₁ := by
  rw [chordSq, chordSq]; ring

/-- The angular increment wrapped to `(−π, π]`. -/
noncomputable def wrap (x : ℝ) : ℝ := ((x : Real.Angle)).toReal

lemma wrap_mem_Ioc (x : ℝ) : wrap x ∈ Set.Ioc (-π) π :=
  Real.Angle.toReal_mem_Ioc _

/-- Cosine does not see the wrap. -/
lemma cos_wrap (x : ℝ) : cos (wrap x) = cos x := by
  obtain ⟨n, hn⟩ : ∃ n : ℤ, n • (2 * π) = x - wrap x := by
    rw [← Real.Angle.coe_eq_zero_iff, Real.Angle.coe_sub]
    simp [wrap, Real.Angle.coe_toReal]
  have hn' : (n : ℝ) * (2 * π) = x - wrap x := by
    rw [← zsmul_eq_mul]; exact hn
  have hx : x = wrap x + (n : ℝ) * (2 * π) := by linarith
  conv_rhs => rw [hx]
  rw [cos_add_int_mul_two_pi]

/-- **The edge–angle bound (Lemma D⁻, step 1).** An edge of squared chord
`< 3·r_min²` between points at radii `≥ r_min > 0` has wrapped angular
increment strictly inside `(−2π/3, 2π/3)`. -/
theorem wrap_lt_of_chordSq_lt {rmin r₁ r₂ θ₁ θ₂ : ℝ} (hrmin : 0 < rmin)
    (h₁ : rmin ≤ r₁) (h₂ : rmin ≤ r₂)
    (hchord : chordSq r₁ θ₁ r₂ θ₂ < 3 * rmin ^ 2) :
    |wrap (θ₁ - θ₂)| < 2 * π / 3 := by
  have hπ := pi_pos
  -- cos of the raw increment exceeds −1/2
  have hcos : -(1 / 2) < cos (θ₁ - θ₂) := by
    rw [chordSq_eq] at hchord
    have hc1 : 0 ≤ 1 - cos (θ₁ - θ₂) := by nlinarith [cos_le_one (θ₁ - θ₂)]
    have hrr : rmin ^ 2 ≤ r₁ * r₂ := by
      nlinarith [mul_le_mul h₁ h₂ hrmin.le (hrmin.le.trans h₁)]
    have hkey : 0 ≤ (r₁ * r₂ - rmin ^ 2) * (1 - cos (θ₁ - θ₂)) :=
      mul_nonneg (by linarith) hc1
    nlinarith [sq_nonneg (r₁ - r₂), mul_pos hrmin hrmin]
  have hcw : -(1 / 2) < cos (wrap (θ₁ - θ₂)) := by rw [cos_wrap]; exact hcos
  by_contra hcon
  rw [not_lt] at hcon
  have h23 : cos (2 * π / 3) = -(1 / 2) := by
    have h : (2 * π / 3 : ℝ) = π - π / 3 := by ring
    rw [h, cos_pi_sub, cos_pi_div_three]
  have hcos_abs : cos |wrap (θ₁ - θ₂)| = cos (wrap (θ₁ - θ₂)) := by
    rcases abs_cases (wrap (θ₁ - θ₂)) with ⟨h, _⟩ | ⟨h, _⟩
    · rw [h]
    · rw [h, cos_neg]
  have habs_le : |wrap (θ₁ - θ₂)| ≤ π := by
    have h := wrap_mem_Ioc (θ₁ - θ₂)
    rw [abs_le]
    exact ⟨by linarith [h.1], h.2⟩
  have hanti : cos |wrap (θ₁ - θ₂)| ≤ cos (2 * π / 3) :=
    Real.strictAntiOn_cos.antitoneOn
      ⟨by positivity, by linarith⟩
      ⟨abs_nonneg _, habs_le⟩ hcon
  rw [hcos_abs, h23] at hanti
  linarith

/-! ## The triangle telescope -/

/-- The wrapped increments of a triangle sum to a multiple of 2π: they
telescope in `ℝ/2πℤ`. -/
lemma wrap_triangle_sum (θ₁ θ₂ θ₃ : ℝ) :
    ∃ k : ℤ, wrap (θ₂ - θ₁) + wrap (θ₃ - θ₂) + wrap (θ₁ - θ₃)
      = (k : ℝ) * (2 * π) := by
  have hcoe : ((wrap (θ₂ - θ₁) + wrap (θ₃ - θ₂) + wrap (θ₁ - θ₃) : ℝ)
      : Real.Angle) = 0 := by
    rw [Real.Angle.coe_add, Real.Angle.coe_add]
    simp only [wrap, Real.Angle.coe_toReal]
    rw [← Real.Angle.coe_add, ← Real.Angle.coe_add,
      show (θ₂ - θ₁) + (θ₃ - θ₂) + (θ₁ - θ₃) = (0 : ℝ) by ring,
      Real.Angle.coe_zero]
  obtain ⟨n, hn⟩ := Real.Angle.coe_eq_zero_iff.mp hcoe
  refine ⟨n, ?_⟩
  rw [← hn, zsmul_eq_mul]

/-- **Every triangle boundary has winding 0 (Lemma D⁻, step 2).** When each
wrapped increment is < 2π/3 in absolute value, the telescoped multiple of 2π
is exactly zero. -/
theorem triangle_wrap_sum_eq_zero {θ₁ θ₂ θ₃ : ℝ}
    (h₁₂ : |wrap (θ₂ - θ₁)| < 2 * π / 3)
    (h₂₃ : |wrap (θ₃ - θ₂)| < 2 * π / 3)
    (h₃₁ : |wrap (θ₁ - θ₃)| < 2 * π / 3) :
    wrap (θ₂ - θ₁) + wrap (θ₃ - θ₂) + wrap (θ₁ - θ₃) = 0 := by
  obtain ⟨k, hk⟩ := wrap_triangle_sum θ₁ θ₂ θ₃
  have hπ := pi_pos
  obtain ⟨ha₁, ha₂⟩ := abs_lt.mp h₁₂
  obtain ⟨hb₁, hb₂⟩ := abs_lt.mp h₂₃
  obtain ⟨hc₁, hc₂⟩ := abs_lt.mp h₃₁
  have hk1 : (-1 : ℤ) < k := by
    have : (-1 : ℝ) < (k : ℝ) := by nlinarith
    exact_mod_cast this
  have hk2 : k < (1 : ℤ) := by
    have : ((k : ℝ)) < 1 := by nlinarith
    exact_mod_cast this
  have hk0 : k = 0 := by omega
  rw [hk, hk0]
  push_cast
  ring

/-! ## Chains and the winding functional -/

section Chains

variable {ι : Type*}

/-- The winding of a 1-chain (a finitely supported ℤ-combination of oriented
edges) against an increment assignment `δ`. -/
noncomputable def winding (δ : ι × ι → ℝ) (z : (ι × ι) →₀ ℤ) : ℝ :=
  z.sum fun e n => n • δ e

lemma winding_zero (δ : ι × ι → ℝ) : winding δ 0 = 0 :=
  Finsupp.sum_zero_index

lemma winding_add (δ : ι × ι → ℝ) (a b : (ι × ι) →₀ ℤ) :
    winding δ (a + b) = winding δ a + winding δ b :=
  Finsupp.sum_add_index' (fun e => zero_smul ℤ (δ e))
    (fun e m n => add_smul m n (δ e))

lemma winding_neg (δ : ι × ι → ℝ) (a : (ι × ι) →₀ ℤ) :
    winding δ (-a) = -winding δ a := by
  have h := winding_add δ (-a) a
  rw [neg_add_cancel, winding_zero] at h
  linarith

lemma winding_single (δ : ι × ι → ℝ) (e : ι × ι) :
    winding δ (Finsupp.single e 1) = δ e := by
  rw [winding, Finsupp.sum_single_index (zero_smul ℤ (δ e)), one_smul]

/-- The boundary of the oriented triangle `(i, j, k)`. -/
noncomputable def triangleBoundary (i j k : ι) : (ι × ι) →₀ ℤ :=
  Finsupp.single (i, j) 1 + Finsupp.single (j, k) 1 + Finsupp.single (k, i) 1

lemma winding_triangleBoundary (δ : ι × ι → ℝ) (i j k : ι) :
    winding δ (triangleBoundary i j k) = δ (i, j) + δ (j, k) + δ (k, i) := by
  rw [triangleBoundary, winding_add, winding_add,
    winding_single, winding_single, winding_single]

/-- **The homology step of Lemma D⁻, abstractly**: winding is additive and
vanishes on every generator, so it vanishes on the generated subgroup — a
chain with nonzero winding is not a combination of the given boundaries. -/
theorem winding_notin_boundaries {δ : ι × ι → ℝ}
    {B : Set ((ι × ι) →₀ ℤ)} (hB : ∀ b ∈ B, winding δ b = 0)
    {z : (ι × ι) →₀ ℤ} (hz : winding δ z ≠ 0) :
    z ∉ AddSubgroup.closure B := by
  intro hmem
  apply hz
  exact AddSubgroup.closure_induction (fun b hb => hB b hb) (winding_zero δ)
    (fun a b _ _ ha hb => by rw [winding_add, ha, hb, add_zero])
    (fun a _ ha => by rw [winding_neg, ha, neg_zero]) hmem

end Chains

/-! ## Lemma D⁻'s core, composed -/

/-- **Lemma D⁻, the mathematical content.** Samples at radii `≥ r_min > 0`
with angles `θ`; scale `s` with `s² < 3·r_min²` (i.e. `s < √3·r_min`); `B` a
set of oriented-triangle boundaries all of whose edges have squared chord
`≤ s²`. Then any 1-chain whose winding (sum of wrapped angular increments)
is nonzero is NOT in the subgroup generated by `B`: below `√3·r_min`, the
winding class is not a boundary. -/
theorem lemmaDminus_core {ι : Type*} (r θ : ι → ℝ) {rmin s : ℝ}
    (hrmin : 0 < rmin) (hr : ∀ i, rmin ≤ r i) (hs : s ^ 2 < 3 * rmin ^ 2)
    {B : Set ((ι × ι) →₀ ℤ)}
    (hB : ∀ b ∈ B, ∃ i j k, b = triangleBoundary i j k ∧
      chordSq (r i) (θ i) (r j) (θ j) ≤ s ^ 2 ∧
      chordSq (r j) (θ j) (r k) (θ k) ≤ s ^ 2 ∧
      chordSq (r k) (θ k) (r i) (θ i) ≤ s ^ 2)
    {z : (ι × ι) →₀ ℤ}
    (hz : winding (fun e => wrap (θ e.2 - θ e.1)) z ≠ 0) :
    z ∉ AddSubgroup.closure B := by
  apply winding_notin_boundaries ?_ hz
  intro b hb
  obtain ⟨i, j, k, rfl, hij, hjk, hki⟩ := hB b hb
  rw [winding_triangleBoundary]
  have hij' : |wrap (θ j - θ i)| < 2 * π / 3 :=
    wrap_lt_of_chordSq_lt hrmin (hr j) (hr i)
      (lt_of_le_of_lt ((chordSq_comm _ _ _ _).trans_le hij) hs)
  have hjk' : |wrap (θ k - θ j)| < 2 * π / 3 :=
    wrap_lt_of_chordSq_lt hrmin (hr k) (hr j)
      (lt_of_le_of_lt ((chordSq_comm _ _ _ _).trans_le hjk) hs)
  have hki' : |wrap (θ i - θ k)| < 2 * π / 3 :=
    wrap_lt_of_chordSq_lt hrmin (hr i) (hr k)
      (lt_of_le_of_lt ((chordSq_comm _ _ _ _).trans_le hki) hs)
  exact triangle_wrap_sum_eq_zero hij' hjk' hki'

/-! ## Lemma B's gap-jump core

The lower-bound half of Lemma B: a closed walk with nonzero winding on
samples that all avoid an open gap arc must contain an edge whose wrapped
increment is at least the gap width. The formalization works on the LIFTED
cumulative sequence, where no wrapping is needed at all: the lift climbs by
2πw, so it must cross a lift of the gap's midpoint, and both endpoints of
the crossing step keep distance ≥ Δ/2 from that lift — the step is ≥ Δ. The
negative-winding case follows by negating the lifted sequence (which avoids
the wrap-reversal pathology at ±π entirely). -/

/-- Every wrap differs from its argument by an integer multiple of 2π. -/
lemma wrap_eq_add_int (x : ℝ) : ∃ p : ℤ, wrap x = x + (p : ℝ) * (2 * π) := by
  obtain ⟨n, hn⟩ : ∃ n : ℤ, n • (2 * π) = x - wrap x := by
    rw [← Real.Angle.coe_eq_zero_iff, Real.Angle.coe_sub]
    simp [wrap, Real.Angle.coe_toReal]
  have hn' : (n : ℝ) * (2 * π) = x - wrap x := by
    rw [← zsmul_eq_mul]; exact hn
  refine ⟨-n, ?_⟩
  push_cast
  linarith

/-- Every real has a lift of `g` within one period above it. -/
lemma exists_lift_above (g x : ℝ) :
    ∃ p : ℤ, x < g + (p : ℝ) * (2 * π) ∧ g + (p : ℝ) * (2 * π) ≤ x + 2 * π := by
  have hπ := pi_pos
  have h2π : (0 : ℝ) < 2 * π := by linarith
  refine ⟨⌊(x - g) / (2 * π)⌋ + 1, ?_, ?_⟩
  · have h := Int.lt_floor_add_one ((x - g) / (2 * π))
    have h2 : (x - g) / (2 * π) * (2 * π) = x - g := by field_simp
    push_cast
    nlinarith
  · have h := Int.floor_le ((x - g) / (2 * π))
    have h2 : (x - g) / (2 * π) * (2 * π) = x - g := by field_simp
    push_cast
    nlinarith

/-- **The upcrossing lemma.** A finite real sequence that climbs by at least
2π while keeping distance ≥ Δ/2 from every lift of `g` must take a single
step of size ≥ Δ. -/
lemma exists_big_step_of_climb {n : ℕ} {ψ : ℕ → ℝ} {g Δ : ℝ} (hΔ0 : 0 < Δ)
    (hclimb : ψ 0 + 2 * π ≤ ψ n)
    (hgap : ∀ k ≤ n, ∀ p : ℤ, Δ / 2 ≤ |ψ k - (g + (p : ℝ) * (2 * π))|) :
    ∃ k < n, Δ ≤ ψ (k + 1) - ψ k := by
  classical
  have hπ := pi_pos
  obtain ⟨p, hp1, hp2⟩ := exists_lift_above g (ψ 0)
  set m := g + (p : ℝ) * (2 * π) with hm
  have hψn : m < ψ n := by
    rcases lt_or_eq_of_le (by linarith : m ≤ ψ n) with h | h
    · exact h
    · exfalso
      have hg := hgap n le_rfl p
      rw [← hm, ← h, sub_self, abs_zero] at hg
      linarith
  set K := Nat.findGreatest (fun j => ψ j ≤ m) n with hK
  have hKspec : ψ K ≤ m := by
    have h := Nat.findGreatest_spec (P := fun j => ψ j ≤ m)
      (Nat.zero_le n) hp1.le
    exact h
  have hKle : K ≤ n := Nat.findGreatest_le n
  have hKn : K < n := by
    rcases lt_or_eq_of_le hKle with h | h
    · exact h
    · exfalso; rw [h] at hKspec; linarith
  have hK1 : m < ψ (K + 1) := by
    have h := Nat.findGreatest_is_greatest (P := fun j => ψ j ≤ m)
      (by omega : K < K + 1) (by omega : K + 1 ≤ n)
    exact not_le.mp h
  have hdK : Δ / 2 ≤ m - ψ K := by
    have h := hgap K hKle p
    rw [← hm, abs_of_nonpos (by linarith)] at h
    linarith
  have hdK1 : Δ / 2 ≤ ψ (K + 1) - m := by
    have h := hgap (K + 1) (by omega) p
    rw [← hm, abs_of_nonneg (by linarith)] at h
    linarith
  exact ⟨K, hKn, by linarith⟩

/-- **Lemma B's gap-jump core (the lower-bound half).** A walk whose wrapped
increments sum to `2πw` with `w ≠ 0`, on vertices whose angles all keep
distance ≥ Δ/2 from every lift of the gap midpoint `g` (i.e. no vertex in
the open gap arc of width Δ), has a step with `|wrapped increment| ≥ Δ`.
With the chord–angle bound (`chordSq_eq`; the chord between radii ≥ r_min at
angular separation ≥ Δ is ≥ 2·r_min·sin(Δ/2)), this is the birth lower bound
`s_w ≥ 2·r_min·sin(Δθ_max/2)`. -/
theorem lemmaB_gap_jump {n : ℕ} (θw : ℕ → ℝ) {g Δ : ℝ} {w : ℤ}
    (hΔ0 : 0 < Δ) (hw : w ≠ 0)
    (hsum : ∑ k ∈ Finset.range n, wrap (θw (k + 1) - θw k) = (w : ℝ) * (2 * π))
    (hgap : ∀ k ≤ n, ∀ p : ℤ, Δ / 2 ≤ |θw k - (g + (p : ℝ) * (2 * π))|) :
    ∃ k < n, Δ ≤ |wrap (θw (k + 1) - θw k)| := by
  classical
  have hπ := pi_pos
  set ψ := fun j => θw 0 + ∑ i ∈ Finset.range j, wrap (θw (i + 1) - θw i)
    with hψ
  have hstep : ∀ k, ψ (k + 1) - ψ k = wrap (θw (k + 1) - θw k) := by
    intro k
    simp only [hψ]
    rw [Finset.sum_range_succ]
    ring
  have hlift : ∀ k, ∃ q : ℤ, ψ k = θw k + (q : ℝ) * (2 * π) := by
    intro k
    induction k with
    | zero => exact ⟨0, by simp [hψ]⟩
    | succ j ih =>
      obtain ⟨q, hq⟩ := ih
      obtain ⟨p, hp⟩ := wrap_eq_add_int (θw (j + 1) - θw j)
      refine ⟨q + p, ?_⟩
      have hs := hstep j
      rw [hp] at hs
      push_cast
      linarith
  have hgapψ : ∀ k ≤ n, ∀ p : ℤ, Δ / 2 ≤ |ψ k - (g + (p : ℝ) * (2 * π))| := by
    intro k hk p
    obtain ⟨q, hq⟩ := hlift k
    have h := hgap k hk (p - q)
    rw [hq, show θw k + (q : ℝ) * (2 * π) - (g + (p : ℝ) * (2 * π))
      = θw k - (g + ((p - q : ℤ) : ℝ) * (2 * π)) by push_cast; ring]
    exact h
  have hψn : ψ n = ψ 0 + (w : ℝ) * (2 * π) := by
    simp only [hψ, Finset.sum_range_zero, hsum]
    ring
  rcases lt_or_gt_of_ne hw with hneg | hpos
  · -- negative winding: negate the lifted sequence
    have hw1 : (1 : ℝ) ≤ -(w : ℝ) := by
      have : w ≤ -1 := by omega
      have h' : (w : ℝ) ≤ -1 := by exact_mod_cast this
      linarith
    have hclimb : (fun j => -ψ j) 0 + 2 * π ≤ (fun j => -ψ j) n := by
      simp only
      nlinarith
    have hgap' : ∀ k ≤ n, ∀ p : ℤ,
        Δ / 2 ≤ |(fun j => -ψ j) k - (-g + (p : ℝ) * (2 * π))| := by
      intro k hk p
      have h := hgapψ k hk (-p)
      rw [show (fun j => -ψ j) k - (-g + (p : ℝ) * (2 * π))
        = -(ψ k - (g + ((-p : ℤ) : ℝ) * (2 * π))) by push_cast; ring, abs_neg]
      exact h
    obtain ⟨k, hk, hbig⟩ := exists_big_step_of_climb hΔ0 hclimb hgap'
    refine ⟨k, hk, ?_⟩
    have hbig' : Δ ≤ -ψ (k + 1) - -ψ k := hbig
    have : Δ ≤ -(ψ (k + 1) - ψ k) := by linarith
    rw [hstep k] at this
    exact le_trans this (neg_le_abs _)
  · -- positive winding
    have hw1 : (1 : ℝ) ≤ (w : ℝ) := by exact_mod_cast hpos
    have hclimb : ψ 0 + 2 * π ≤ ψ n := by nlinarith
    obtain ⟨k, hk, hbig⟩ := exists_big_step_of_climb hΔ0 hclimb hgapψ
    refine ⟨k, hk, ?_⟩
    rw [← hstep k]
    exact le_trans hbig (le_abs_self _)

end RipsCircle

end Paper3Ring
