"""Claim B exploratory probe (imperfect-info, real LLM synthesis on Beacon).

Question: is the INFERENCE surface (observation/infer_states) translation-not-
inference too? Synthesize Beacon (non-contaminated; we invented it) two ways:
  (full)     rules include HOW the type is revealed (a move at step k by type t is
             (k+t)%2 -> the type is recoverable from observed moves);
  (withheld) the revelation rule is removed -> the spec no longer says the type is
             inferable from moves.
For each: transition gate (accuracy on random transitions) AND inference gate
(observation_rate / inference_rate on states where the opponent has ALREADY moved,
so narrowing SHOULD happen). The hypothesis: full -> both gates pass; withheld ->
transition gate still passes (blind to inference) but inference_rate drops (the
synthesized infer_states fails to narrow / is wrong) -> the inference surface is a
new failure mode invisible to a transition gate.

Run: PYTHONPATH=src python3.12 scripts/beacon_claimB_probe.py [large|mini]
"""
import os
import sys
import random
from dotenv import load_dotenv
load_dotenv("/Users/javieraguilarmartin1/Documents/repos/code-world-models/.env", override=True)

from cwm.groundtruth import beacon as B
from cwm.world_model import build_imperfect_contract
from cwm.trajectories import Trajectory
from cwm.llm.azure_openai import AzureOpenAIProvider
from cwm.synthesizer import synthesize_cwm
from cwm.refiner import refine_cwm
from cwm.gap import inference_accuracy
from cwm.run_gap import _load_module_from_code

SIZE = sys.argv[1] if len(sys.argv) > 1 else "large"
MODEL = os.environ[{"mini": "AZURE_DEPLOYMENT_MINI", "large": "AZURE_DEPLOYMENT_LARGE",
                    "nano": "AZURE_DEPLOYMENT_NANO"}[SIZE]]
T = 6
truth = B.make_beacon(T)

provider = AzureOpenAIProvider(
    endpoint=os.environ["AZURE_OPENAI_ENDPOINT"], api_key=os.environ["AZURE_OPENAI_API_KEY"],
    api_version=os.environ["AZURE_OPENAI_API_VERSION"])

# The revelation rule (present in full, removed in withheld). Matches the exact
# multi-line wrapping in beacon.RULES_TEXT.
REVEAL = ("type label —\n    which is recoverable from their observed moves, since "
          "a move at step k by a\n    player of type t is (k + t) % 2.")
RULES_FULL = B.RULES_TEXT
RULES_WITHHELD = RULES_FULL.replace(REVEAL, "type label.")
assert RULES_WITHHELD != RULES_FULL, "revelation-rule replace was a no-op — check REVEAL text"
assert "recoverable" not in RULES_WITHHELD, "reveal rule still present in withheld variant"


def collect_transitions(model, n_games, seed):
    rng = random.Random(seed)
    deals = model.initial_states()
    out = []
    for _ in range(n_games):
        d = deals[rng.randrange(len(deals))]
        s = {"board": list(d["board"]), "current_player": d["current_player"]}
        while not model.is_terminal(s):
            legal = model.legal_actions(s)
            a = rng.choice(legal)
            nxt = model.apply_action(s, a)
            out.append(Trajectory(state=s, action=a, next_state=nxt,
                                  reward=model.returns(nxt), terminal=model.is_terminal(nxt),
                                  legal_actions=legal))
            s = nxt
    return out


def post_move_states(model, n, seed):
    """States where the OPPONENT has already moved (so true infer_states narrows to a
    singleton) — the states a transition gate's random sample under-covers but where
    inference actually matters. Generated by safe-policy self-play."""
    rng = random.Random(seed)
    deals = model.initial_states()
    out = []
    while len(out) < n:
        d = deals[rng.randrange(len(deals))]
        s = {"board": list(d["board"]), "current_player": d["current_player"]}
        while not model.is_terminal(s):
            b = s["board"]
            if b[4] != -1 and b[5] != -1:        # both have moved -> narrowing applies
                out.append({"board": list(b), "current_player": s["current_player"]})
            p = s["current_player"]
            k = b[0] if p == 1 else b[1]
            t = b[2] if p == 1 else b[3]
            if b[8] == 1:                        # final round: guess anything legal
                s = model.apply_action(s, 0)
            else:
                s = model.apply_action(s, model.safe(k, t))
    return out[:n]


def run(label, rules):
    print(f"\n=== {label} ===", flush=True)
    contract = build_imperfect_contract(rules)
    traj = collect_transitions(truth, n_games=120, seed=1)
    code, _ = synthesize_cwm(provider, MODEL, contract, traj)
    refined = refine_cwm(provider, MODEL, contract, code, traj, max_iters=10)
    print(f"transition gate: accuracy={refined.accuracy:.4f} iters={refined.iterations}",
          flush=True)
    sample = post_move_states(truth, 40, seed=2)
    inf = inference_accuracy(refined.code, sample, truth)
    print(f"inference gate (post-move states): observation_rate={inf['observation_rate']:.3f} "
          f"inference_rate={inf['inference_rate']:.3f} n={inf['n']} exec_err={inf['n_exec_errors']}",
          flush=True)
    if inf["examples"]:
        print("  examples:", inf["examples"][:2], flush=True)
    return {"label": label, "transition_acc": refined.accuracy,
            "observation_rate": inf["observation_rate"], "inference_rate": inf["inference_rate"]}


def main():
    print(f"Claim B probe on Beacon (T={T}), synth size={SIZE}", flush=True)
    r_full = run("FULL rules", RULES_FULL)
    r_wh = run("WITHHELD revelation rule", RULES_WITHHELD)
    print("\n=== SUMMARY ===", flush=True)
    for r in (r_full, r_wh):
        print(f"{r['label']:28s} transition_acc={r['transition_acc']:.3f} "
              f"observation_rate={r['observation_rate']:.3f} "
              f"inference_rate={r['inference_rate']:.3f}", flush=True)
    print("DONE", flush=True)


if __name__ == "__main__":
    main()
